orchestratorConfig:
  cron: "H H/4 * * *"
  testConfig:
  - testToLaunch: fairseq_fork/Tests/Test_fairseq_fork_gaudi_hls_asic_pytorch_fairseq_topology
  - testToLaunch: fairseq_fork/Tests/Test_fairseq_fork_gaudi2_asic_pytorch_fairseq_topology
stepConfig:
  jobTimeout: '250'